<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * The nationally unique 10-digit 医療機関コード that claims (レセプト) and
     * most medical systems identify a facility by: prefecture (2 digits) +
     * score table number (1 digit: 医科 1, 歯科 3, 薬局 4) + the 7-digit code
     * the bureaus publish (facility_code). Generated by MySQL so it can never
     * drift from its parts, and unique because the 7-digit code is only
     * unique within one prefecture and score table.
     */
    public function up(): void
    {
        Schema::table('medical_facilities', function (Blueprint $table) {
            // institution_type: 1 病院, 2 診療所 (both 医科), 3 歯科診療所, 4 薬局
            $table->char('medical_institution_code', 10)
                ->storedAs("concat(prefecture_code, case institution_type when 1 then '1' when 2 then '1' when 3 then '3' when 4 then '4' end, facility_code)")
                ->after('facility_code');
            $table->unique('medical_institution_code');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('medical_facilities', function (Blueprint $table) {
            $table->dropUnique(['medical_institution_code']);
            $table->dropColumn('medical_institution_code');
        });
    }
};
